{% set name = "libunwind" %}
{% set version = "1.8.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 21b26bc75cd37b548d7952f2794cde711efa6c6151c4147cc3c52cfedbf11df4 

build:
  number: 1
  skip: true  # [not linux]
  run_exports:
    # breaks backwards compatibility sometimes but we trust the maintainers that they were only internal
    # https://abi-laboratory.pro/index.php?view=timeline&l=libunwind
    - {{ pin_subpackage('libunwind', max_pin='x') }}

requirements:
  build:
    - {{ stdlib('c') }}
    - {{ compiler('c') }}
    - make
    - autoconf
    - automake
    - libtool

test:
  commands:
    - test -f "${PREFIX}/lib/libunwind.so"
    - test ! -f "${PREFIX}/lib/libunwind.a"
    - test -f "${PREFIX}/include/libunwind.h"
    - test -f "${PREFIX}/include/unwind.h"

about:
  home: https://www.nongnu.org/libunwind
  license: MIT
  license_family: MIT
  license_file: COPYING
  summary: 'Defines a portable and efficient C programming interface (API) to determine the call-chain of a program'
  description: 'libunwind is a portable and efficient C API for determining the current call chain of ELF program threads of execution and for resuming execution at any point in that call chain. The API supports both local (same process) and remote (other process) operation.'
  doc_url: https://www.nongnu.org/libunwind/docs.html
  dev_url: https://github.com/libunwind/libunwind

extra:
  recipe-maintainers:
    - synapticarbors
    - xhochy
    - matthiasdiener
