travis:
  secure:
    BINSTAR_TOKEN: wmzDg+fZQHeVSFmnITJHxvyoUdYgJrwyz8/+zM9PFo/85D/JbPIAwHWRO2aEGUu9yjCZYi4sqEa5coJOrk2vGJe5Uk7lAe0xx37cB46qDIoYT3HBhu5pKwZWGMAcibktH7gqoEDBssCKgWvX2idPOgY/xzKJQeCpviCibHV0t1tgwAKEl/7/HarhWTYCZuZ30jOz/lCO3U/dYD8URd6z/yLu0092zwqfJWRUSe1oHrWF49LPRF04IETnlknd7SiOATrJl+Kl0tm1WJZAMJi8Yi9bnUlQZxFG1ecyCyzLgB3OVemt318Q/r6KerQ4wHj7Xsqpkm3p0oRgliTu3zOKywsohsqpgP0RoVswt2bfSvhcseTNidrhoizOgkjcFpG6FdsvtTU4QK3sQa/fcXo7oOtQyO5Mcy3eTbDTKJP+U0UIxtp7mdDTEkAs4Byv/VVGPzsKXAyYdHkdCy/9gHkZKTMTzIOUBwmRyR/6avHSz6ExN8s9WnR8zFCHWj5GuOVXJzk0vod6NZfBOAhwdfT+7pXOFmF21M+PMjtQ1gzeLQk6mVSD3hI0wBHLBIPOxtSdlsAFFas4kMqMQV4K+1zdcfoROO44xei5Oa8eMxMgtR5tnGawVqb8EX2yVMR+VKp5mtBrr8ANyNexphfR8q6XTdQoTIi2LTE7RDEaAqVyAx4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
